direction: down

GitHub : {
    label: Starten aus GitHub
    style: {
        stroke: blue
        stroke-dash: 3
        fill: transparent
    }

    exists : {
        label: "Existiert bereits ein Codespace?"
        shape: image
        icon: ./src/diagrams/img/does-codespace-exist.png
    }

    create : {
        label: "Codespace erstellen"
    }

    exists -> create: "Nein"

    open : {
        label: "Codespace im VS Code öffnen"
        shape: image
        icon: ./src/diagrams/img/open-existing-codespace.png
    }

    exists -> open: "Ja"
}

VSCode : {
    label: "Starten aus VS Code"
    style: {
        stroke: blue
        stroke-dash: 3
        fill: transparent
    }
    near: bottom-center
    
    connect-to : {
        label: Connect To
        shape: image
        icon: ./src/diagrams/img/connect-to.png
    }
    
    connect-to-codespace : {
        label: "Codespace"
        shape: image
        icon: ./src/diagrams/img/connect-to-codespace.png
    }

    connect-to -> connect-to-codespace -> select-codespace
    
    search : {
        label: "Search"
        shape: image
        icon: ./src/diagrams/img/search.png
    }
    
    show-and-run-command : {
        label: "Show and Run Command"
        shape: image
        icon: ./src/diagrams/img/show-and-run-command.png
    }
    
    enter-connect-to-codespace : {
        label: "Eingabe 'Connect to Codespace'"
        shape: image
        icon: ./src/diagrams/img/enter-connect-to-codespace.png
    }
    
    search -> show-and-run-command -> enter-connect-to-codespace -> select-codespace
    
    select-codespace : {
        label: "Auswahl des richtigen vorab erstellen Codespace aus dem richtigen Repository"
    }
}